server:
  port: 9000
  
zuul:
  ignoredServices: '*'
  routes:
    client: 
      path: /client/**
      serviceId: client-service 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/